---
title: "Teaching"
---

<br>

## Instructor

-   **MATH/STAT 355\***: Statistical Theory. Macalester College (2 sections)

    -   [Course notes](https://mac-stat.github.io/MathStat355Notes/)
    -   Recent [course website](https://taylorokonek.github.io/mathstat355_sp25/)

-   **MATH/STAT 354**: Probability. Macalester College (2 sections, Fall 2025)

    -   Current [course website](https://taylorokonek.github.io/mathstat354_fa25/)

-   **STAT 155**: Introduction to Statistical Modeling. Macalester College (7 sections)

    -   [Course notes](https://mac-stat.github.io/Stat155Notes/)

    -   Recent [course website](https://taylorokonek.github.io/stat155_sp25/)

-   **BIOST 311**: Regression Methods in the Health Sciences. University of Washington, Spring 2022. Instructor of record with [Charlie Wolock](https://cwolock.github.io/teaching).

    -   [Course materials](https://github.com/cwolock/BIOST311)

\*MATH/STAT 455: Mathematical Statistics became MATH/STAT 355: Statistical Theory during the 2024-2025 academic year.

<br>

## Teaching Assistant

-   **BIOST 555**: Statistical Methods for Spatial Epidemiology. University of Washington, Winter 2022.

-   **Summer Institute in Statistics and Modeling in Infectious Diseases**: Spatial Statistics in Epidemiology and Public Health. University of Washington, July 2021 and 2022.

-   **BIOST 310**: Biostatistics for the Health Sciences. University of Washington, Fall 2020. Lead TA.
